services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=sms_fraud'
      - 'POSTGRES_PASSWORD=sms_pass'
      - 'POSTGRES_USER=sms_app'
    ports:
      - '5432:5432'
