ALTER TABLE sms_scans ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE sms_scans ALTER COLUMN verdict DROP NOT NULL;
ALTER TABLE sms_scans ADD COLUMN IF NOT EXISTS source VARCHAR(50) DEFAULT 'MANUAL_QUERY';
ALTER TABLE sms_scans ADD COLUMN IF NOT EXISTS is_scam BOOLEAN DEFAULT TRUE;
ALTER TABLE sms_scans ALTER COLUMN is_scam DROP NOT NULL;
